#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Minicli\App;
use App\DigitalOceanService as DigitalOcean;
use Minicli\Util\FileCache;

$app = new App(require __DIR__ . '/config.php');
$cache = new FileCache(__DIR__ . '/var/cache');

$signature = <<<EOD
         ,gggggggggggg,
        dP"""88""""""Y8b,               ,dPYb,             ,dPYb,
        Yb,  88       `8b,              IP'`Yb             IP'`Yb
         `"  88        `8b              I8  8I             I8  8I      gg
             88         Y8              I8  8'             I8  8'      ""
             88         d8   ,ggggg,    I8 dP  gg,gggg,    I8 dPgg,    gg    ,ggg,,ggg,
             88        ,8P  dP"  "Y8ggg I8dP   I8P"  "Yb   I8dP" "8I   88   ,8" "8P" "8,
             88       ,8P' i8'    ,8I   I8P    I8'    ,8i  I8P    I8   88   I8   8I   8I
             88______,dP' ,d8,   ,d8'  ,d8b,_ ,I8 _  ,d8' ,d8     I8,_,88,_,dP   8I   Yb,
            888888888P"   P"Y8888P"    8P'"Y88PI8 YY88888P88P     `Y88P""Y88P'   8I   `Y8
                                               I8
                                               I8
                                               I8
                                               I8
                                               I8
                                               I8
usage: ./dolphin help
EOD;

$app->setSignature($signature);

$app->addService('digitalocean', new DigitalOcean($cache));
$app->runCommand($argv);
